-- Real pricing data for Toolradar tools - December 2025

-- AI Assistants
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://openai.com/chatgpt/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["GPT-4o access","Limited messages","Basic features"]},{"name":"Plus","price":20,"period":"month","features":["GPT-4o & reasoning models","300 premium requests/month","DALL-E image generation"],"highlighted":true},{"name":"Pro","price":200,"period":"month","features":["Unlimited access to all models","o1 pro mode","Priority access"]},{"name":"Team","price":25,"period":"user/month","features":["Everything in Plus","Team workspace","Admin controls"]}]}'::jsonb WHERE slug = 'chatgpt';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://claude.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Claude access","Limited daily usage","Web & mobile apps"]},{"name":"Pro","price":20,"period":"month","features":["5x more usage","Priority access to Claude","Early access to new features"],"highlighted":true},{"name":"Max 5x","price":100,"period":"month","features":["5x Pro usage","For heavy users","All Pro features"]},{"name":"Max 20x","price":200,"period":"month","features":["20x Pro usage","Claude Code workloads","Maximum capacity"]}]}'::jsonb WHERE slug = 'claude';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":30,"pricingPageUrl":"https://one.google.com/about/ai-premium","tiers":[{"name":"Free","price":0,"period":"forever","features":["Gemini access","Basic features","Limited usage"]},{"name":"AI Pro","price":19.99,"period":"month","features":["2TB storage","Gemini with higher limits","Deep Research","Video generation"],"highlighted":true},{"name":"AI Ultra","price":249.99,"period":"month","features":["30TB storage","Highest model limits","Deep Think","YouTube Premium"]}]}'::jsonb WHERE slug = 'gemini';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://perplexity.ai/pro","tiers":[{"name":"Free","price":0,"period":"forever","features":["Unlimited quick searches","Limited Pro searches","Basic AI models"]},{"name":"Pro","price":20,"period":"month","features":["300+ daily Pro searches","GPT-4 & Claude access","$5 API credits"],"highlighted":true},{"name":"Max","price":200,"period":"month","features":["Advanced AI models","Higher usage limits","Priority support"]}]}'::jsonb WHERE slug = 'perplexity';

-- Coding Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://github.com/features/copilot/plans","tiers":[{"name":"Free","price":0,"period":"forever","features":["Limited Copilot features","For individual developers","Basic completions"]},{"name":"Pro","price":10,"period":"month","features":["300 premium requests","Code completions","Chat in IDE"],"highlighted":true},{"name":"Pro+","price":39,"period":"month","features":["1,500 premium requests","All AI models","Claude & o3 access"]},{"name":"Business","price":19,"period":"user/month","features":["Organization features","Policy management","Audit logs"]}]}'::jsonb WHERE slug = 'github-copilot';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://cursor.com/pricing","tiers":[{"name":"Hobby","price":0,"period":"forever","features":["2,000 completions","50 premium requests","14-day Pro trial"]},{"name":"Pro","price":20,"period":"month","features":["Unlimited completions","$20 usage credit pool","Priority support"],"highlighted":true},{"name":"Ultra","price":200,"period":"month","features":["$400 usage credit","Priority access","Advanced features"]},{"name":"Business","price":40,"period":"user/month","features":["SSO","Admin dashboard","Centralized billing"]}]}'::jsonb WHERE slug = 'cursor';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://codeium.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Unlimited AI features","Autocomplete","In-editor AI chat"]},{"name":"Pro","price":15,"period":"month","features":["Advanced AI models","Extended context","Priority access"],"highlighted":true},{"name":"Teams","price":30,"period":"user/month","features":["Team management","Centralized billing","Analytics"]},{"name":"Enterprise","price":60,"period":"user/month","features":["Private deployment","SSO/RBAC","Custom finetuning"]}]}'::jsonb WHERE slug = 'codeium';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":12,"hasFreeTrial":true,"freeTrialDays":90,"pricingPageUrl":"https://tabnine.com/pricing","tiers":[{"name":"Pro","price":12,"period":"user/month","features":["Best AI models","Personalized AI agents","Basic admin tools"],"highlighted":true},{"name":"Enterprise","price":39,"period":"user/month","features":["Private deployment","Fine-tuned models","Jira integration"]}]}'::jsonb WHERE slug = 'tabnine';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://replit.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Basic features","Community support","Public projects"]},{"name":"Core","price":20,"period":"month","features":["$25 AI credits","GPT-4o & Claude","Private apps"],"highlighted":true},{"name":"Teams","price":40,"period":"user/month","features":["$40 AI credits per user","Team collaboration","Admin controls"]}]}'::jsonb WHERE slug = 'replit-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://bolt.new/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["1M tokens/month","300K daily limit","Basic features"]},{"name":"Pro","price":20,"period":"month","features":["10M tokens","No watermark","Full features"],"highlighted":true},{"name":"Pro 50","price":50,"period":"month","features":["26M tokens","Priority support","Advanced features"]},{"name":"Team","price":30,"period":"user/month","features":["10M tokens per user","Team collaboration","Admin controls"]}]}'::jsonb WHERE slug = 'bolt';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://v0.dev/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["$5 monthly credits","Basic features","UI generation"]},{"name":"Premium","price":20,"period":"month","features":["$20 monthly credits","Figma imports","v0 API access"],"highlighted":true},{"name":"Team","price":30,"period":"user/month","features":["Team workspace","Shared credits","Collaboration"]}]}'::jsonb WHERE slug = 'v0';

-- Design & Image Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":10,"hasFreeTrial":false,"pricingPageUrl":"https://midjourney.com/account","tiers":[{"name":"Basic","price":10,"period":"month","features":["~3.3 fast GPU hours","Standard queue","Commercial rights"]},{"name":"Standard","price":30,"period":"month","features":["15 fast GPU hours","Unlimited relaxed","General commercial use"],"highlighted":true},{"name":"Pro","price":60,"period":"month","features":["30 fast GPU hours","Stealth mode","Faster generations"]},{"name":"Mega","price":120,"period":"month","features":["60 fast GPU hours","Maximum capacity","Enterprise features"]}]}'::jsonb WHERE slug = 'midjourney';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":20,"hasFreeTrial":false,"pricingPageUrl":"https://openai.com/dall-e-3","tiers":[{"name":"ChatGPT Plus","price":20,"period":"month","features":["Included with Plus","Image generation","No per-image fee"],"highlighted":true},{"name":"API Standard","price":0.04,"period":"image","features":["1024x1024","Standard quality","Pay per image"]},{"name":"API HD","price":0.08,"period":"image","features":["1024x1024 HD","Higher quality","Pay per image"]}]}'::jsonb WHERE slug = 'dall-e-3';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://leonardo.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["150 daily tokens","Basic features","Watermarked images"]},{"name":"Apprentice","price":12,"period":"month","features":["8,500 tokens/month","10 custom models","No watermark"],"highlighted":true},{"name":"Artisan","price":30,"period":"month","features":["25,000 tokens/month","Unlimited relaxed","20 custom models"]},{"name":"Maestro","price":60,"period":"month","features":["60,000 tokens/month","Video generation","50 custom models"]}]}'::jsonb WHERE slug = 'leonardo-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":30,"pricingPageUrl":"https://canva.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["50 AI image generations","Basic templates","5GB storage"]},{"name":"Pro","price":15,"period":"month","features":["500 AI images/month","100M+ stock photos","100GB storage"],"highlighted":true},{"name":"Teams","price":10,"period":"user/month","features":["Everything in Pro","Team collaboration","Brand kits"]}]}'::jsonb WHERE slug = 'canva-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://figma.com/pricing","tiers":[{"name":"Starter","price":0,"period":"forever","features":["3 Figma files","Limited AI features","Personal use"]},{"name":"Professional","price":15,"period":"editor/month","features":["Unlimited files","AI features","Version history"],"highlighted":true},{"name":"Organization","price":45,"period":"editor/month","features":["Advanced admin","SSO","Design systems"]}]}'::jsonb WHERE slug = 'figma-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://stability.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Open source model","Self-hosted","Unlimited local use"]},{"name":"API","price":0.002,"period":"image","features":["Cloud generation","Pay per use","High availability"]}]}'::jsonb WHERE slug = 'stable-diffusion';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://ideogram.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Limited generations","Basic features","Watermarked"]},{"name":"Basic","price":7,"period":"month","features":["400 images/month","No watermark","Commercial use"],"highlighted":true},{"name":"Plus","price":16,"period":"month","features":["1,000 images/month","Priority queue","Advanced features"]},{"name":"Pro","price":48,"period":"month","features":["3,000 images/month","Fastest generation","API access"]}]}'::jsonb WHERE slug = 'ideogram';

-- Video & Audio Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://elevenlabs.io/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["10,000 characters/month","3 custom voices","Personal use"]},{"name":"Starter","price":5,"period":"month","features":["30,000 credits","10 custom voices","Commercial license"]},{"name":"Creator","price":22,"period":"month","features":["100,000 credits","30 custom voices","Pro voice cloning"],"highlighted":true},{"name":"Pro","price":99,"period":"month","features":["500,000 credits","160 custom voices","44.1kHz API access"]}]}'::jsonb WHERE slug = 'elevenlabs';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://runwayml.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["125 one-time credits","Watermarked exports","5GB storage"]},{"name":"Standard","price":12,"period":"month","features":["625 credits/month","No watermark","100GB storage"],"highlighted":true},{"name":"Pro","price":28,"period":"month","features":["2,250 credits/month","4K rendering","Priority queue"]},{"name":"Unlimited","price":76,"period":"month","features":["Unlimited explore mode","2,250 credits","Relaxed generations"]}]}'::jsonb WHERE slug = 'runway';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://synthesia.io/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["3 minutes/month","9 AI avatars","Basic features"]},{"name":"Starter","price":29,"period":"month","features":["10 min/month","125+ avatars","3 personal avatars"],"highlighted":true},{"name":"Creator","price":89,"period":"month","features":["30 min/month","180+ avatars","API access"]},{"name":"Enterprise","price":"Custom","features":["Unlimited videos","230+ avatars","Priority support"]}]}'::jsonb WHERE slug = 'synthesia';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://heygen.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["3 videos/month","10 credits","Basic features"]},{"name":"Creator","price":29,"period":"month","features":["15 credits/month","5 min max duration","No watermark"],"highlighted":true},{"name":"Business","price":89,"period":"month","features":["30 credits/month","20 min max","4K resolution"]},{"name":"Enterprise","price":"Custom","features":["Unlimited videos","Custom avatars","SSO"]}]}'::jsonb WHERE slug = 'heygen';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://descript.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["1 hour transcription","720p export","5GB storage"]},{"name":"Hobbyist","price":12,"period":"month","features":["10 hours transcription","1080p export","Unlimited projects"],"highlighted":true},{"name":"Creator","price":24,"period":"month","features":["30 hours transcription","4K export","AI features"]},{"name":"Business","price":40,"period":"month","features":["40 hours transcription","Team collaboration","Priority support"]}]}'::jsonb WHERE slug = 'descript';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://loom.com/pricing","tiers":[{"name":"Starter","price":0,"period":"forever","features":["25 videos/person","5 min max","Basic features"]},{"name":"Business","price":15,"period":"user/month","features":["Unlimited videos","Advanced editing","Custom branding"],"highlighted":true},{"name":"Business AI","price":20,"period":"user/month","features":["AI summaries","Auto chapters","Filler word removal"]},{"name":"Enterprise","price":"Custom","features":["SSO","Advanced security","Dedicated support"]}]}'::jsonb WHERE slug = 'loom-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://murf.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["10 mins generation","Limited voices","Watermarked audio"]},{"name":"Creator","price":19,"period":"month","features":["2 hours/month","120+ voices","Commercial license"],"highlighted":true},{"name":"Business","price":66,"period":"month","features":["8 hours/month","All voices","Team collaboration"]},{"name":"Enterprise","price":"Custom","features":["Unlimited usage","Voice cloning","API access"]}]}'::jsonb WHERE slug = 'murf-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://suno.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["50 credits/day","~10 songs/day","Personal use only"]},{"name":"Pro","price":10,"period":"month","features":["2,500 credits/month","Commercial rights","Song Editor"],"highlighted":true},{"name":"Premier","price":30,"period":"month","features":["10,000 credits/month","Suno Studio","Advanced tools"]}]}'::jsonb WHERE slug = 'suno';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://udio.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["10 daily credits","100 monthly backup","Attribution required"]},{"name":"Standard","price":10,"period":"month","features":["2,400 credits/month","6 concurrent songs","Stem downloads"],"highlighted":true},{"name":"Pro","price":30,"period":"month","features":["6,000 credits/month","8 concurrent songs","Bulk downloads"]}]}'::jsonb WHERE slug = 'udio';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://pika.art/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["150 credits/month","Basic features","Watermarked"]},{"name":"Standard","price":8,"period":"month","features":["700 credits/month","No watermark","Commercial use"],"highlighted":true},{"name":"Unlimited","price":28,"period":"month","features":["2,000 credits/month","Unlimited relaxed","Priority queue"]},{"name":"Pro","price":58,"period":"month","features":["4,000 credits/month","Fastest generation","Advanced features"]}]}'::jsonb WHERE slug = 'pika';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://lumalabs.ai/dream-machine","tiers":[{"name":"Free","price":0,"period":"forever","features":["30 generations/month","Basic features","Watermarked"]},{"name":"Standard","price":9.99,"period":"month","features":["150 generations/month","No watermark","Commercial use"],"highlighted":true},{"name":"Pro","price":29.99,"period":"month","features":["400 generations/month","Priority queue","Extended clips"]},{"name":"Premier","price":99.99,"period":"month","features":["2,000 generations/month","API access","Max quality"]}]}'::jsonb WHERE slug = 'luma-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://invideo.io/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["40 AI mins/week","10 stock exports","Watermarked"]},{"name":"Plus","price":25,"period":"month","features":["100 AI mins/month","50 exports/month","No watermark"],"highlighted":true},{"name":"Max","price":60,"period":"month","features":["200 AI mins/month","200 exports/month","Priority rendering"]}]}'::jsonb WHERE slug = 'invideo';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://opus.pro/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["60 credits/month","Watermarked","Basic features"]},{"name":"Starter","price":19,"period":"month","features":["200 credits/month","No watermark","720p export"],"highlighted":true},{"name":"Pro","price":49,"period":"month","features":["600 credits/month","1080p export","Caption styles"]},{"name":"Pro+","price":119,"period":"month","features":["1,200 credits/month","4K export","API access"]}]}'::jsonb WHERE slug = 'opus-clip';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":19,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://pictory.ai/pricing","tiers":[{"name":"Starter","price":19,"period":"month","features":["30 videos/month","10 min max","Basic features"]},{"name":"Professional","price":39,"period":"month","features":["60 videos/month","20 min max","Premium assets"],"highlighted":true},{"name":"Teams","price":99,"period":"month","features":["90 videos/month","3 users","Collaboration"]}]}'::jsonb WHERE slug = 'pictory';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://play.ht/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Limited characters","Basic voices","Personal use"]},{"name":"Creator","price":31.20,"period":"month","features":["Unlimited words","Voice cloning","Commercial use"],"highlighted":true},{"name":"Unlimited","price":99,"period":"month","features":["Unlimited everything","All features","Priority support"]}]}'::jsonb WHERE slug = 'play-ht';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":3,"pricingPageUrl":"https://speechify.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Limited listening","Basic voices","Web only"]},{"name":"Premium","price":139,"period":"year","features":["Unlimited listening","30+ voices","All platforms"],"highlighted":true},{"name":"Studio","price":29,"period":"month","features":["Voice cloning","API access","Commercial use"]}]}'::jsonb WHERE slug = 'speechify';

-- Productivity & Writing Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://notion.so/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Basic Notion","20 AI responses total","Personal use"]},{"name":"Plus","price":10,"period":"user/month","features":["Unlimited blocks","Limited AI trial","30-day history"],"highlighted":true},{"name":"Business","price":20,"period":"user/month","features":["AI included","SAML SSO","Private teamspaces"]},{"name":"Enterprise","price":"Custom","features":["Advanced security","Audit log","Dedicated support"]}]}'::jsonb WHERE slug = 'notion-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":39,"hasFreeTrial":true,"freeTrialDays":7,"pricingPageUrl":"https://jasper.ai/pricing","tiers":[{"name":"Creator","price":39,"period":"month","features":["Unlimited words","50+ templates","1 brand voice"],"highlighted":true},{"name":"Pro","price":59,"period":"month","features":["All features","Multiple brands","Team collaboration"]},{"name":"Business","price":"Custom","features":["API access","SSO","Custom integrations"]}]}'::jsonb WHERE slug = 'jasper';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://copy.ai/prices","tiers":[{"name":"Free","price":0,"period":"forever","features":["2,000 words/month","1 user","90+ templates"]},{"name":"Pro","price":36,"period":"month","features":["Unlimited words","5 users","25+ languages"],"highlighted":true},{"name":"Team","price":186,"period":"month","features":["20 users","Priority support","Collaboration tools"]},{"name":"Enterprise","price":"Custom","features":["Unlimited users","API access","Custom workflows"]}]}'::jsonb WHERE slug = 'copy-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://grammarly.com/plans","tiers":[{"name":"Free","price":0,"period":"forever","features":["Basic writing corrections","Tone detection","Limited AI"]},{"name":"Pro","price":12,"period":"month","features":["Advanced corrections","Plagiarism detection","2,000 AI prompts"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Admin controls","SSO","Priority support"]}]}'::jsonb WHERE slug = 'grammarly';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://wordtune.com/plans","tiers":[{"name":"Free","price":0,"period":"forever","features":["10 rewrites/day","Basic features","English only"]},{"name":"Plus","price":9.99,"period":"month","features":["Unlimited rewrites","Summarization","All languages"],"highlighted":true},{"name":"Unlimited","price":14.99,"period":"month","features":["Everything in Plus","Premium support","Priority access"]}]}'::jsonb WHERE slug = 'wordtune';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":7,"pricingPageUrl":"https://writesonic.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["10,000 words/month","100+ templates","1 project"]},{"name":"Individual","price":16,"period":"month","features":["100,000 words/month","Unlimited projects","GPT-4 access"],"highlighted":true},{"name":"Team","price":13,"period":"user/month","features":["Everything in Individual","Team workspace","Collaboration"]}]}'::jsonb WHERE slug = 'writesonic';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://mem.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Basic features","Limited AI","Personal use"]},{"name":"Pro","price":10,"period":"month","features":["Unlimited AI","Smart search","Integrations"],"highlighted":true},{"name":"Business","price":25,"period":"user/month","features":["Team features","Admin controls","SSO"]}]}'::jsonb WHERE slug = 'mem';

-- Meeting & Transcription Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://otter.ai/pricing","tiers":[{"name":"Basic","price":0,"period":"forever","features":["300 min/month","30 min/meeting","3 imports/month"]},{"name":"Pro","price":8.33,"period":"month","features":["1,200 min/month","90 min/meeting","Advanced search"],"highlighted":true},{"name":"Business","price":20,"period":"user/month","features":["6,000 min/month","4 hours/meeting","Unlimited imports"]},{"name":"Enterprise","price":"Custom","features":["Unlimited transcription","SSO","Sales features"]}]}'::jsonb WHERE slug = 'otter-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://fireflies.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Unlimited transcription","800 min storage","Limited AI summaries"]},{"name":"Pro","price":10,"period":"month","features":["Unlimited storage","CRM integration","More AI features"],"highlighted":true},{"name":"Business","price":19,"period":"user/month","features":["Unlimited everything","Analytics","API access"]},{"name":"Enterprise","price":39,"period":"user/month","features":["SSO","HIPAA compliance","Dedicated support"]}]}'::jsonb WHERE slug = 'fireflies-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://reclaim.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["1 calendar","Smart scheduling","Basic features"]},{"name":"Starter","price":8,"period":"user/month","features":["2 calendars","Scheduling links","Analytics"],"highlighted":true},{"name":"Business","price":12,"period":"user/month","features":["Team scheduling","No-meeting days","Priority support"]},{"name":"Enterprise","price":18,"period":"user/month","features":["SSO","Admin controls","SLA"]}]}'::jsonb WHERE slug = 'reclaim-ai';

-- Automation Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://zapier.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["100 tasks/month","2-step Zaps","AI features"]},{"name":"Professional","price":19.99,"period":"month","features":["750 tasks/month","Multi-step Zaps","Premium apps"],"highlighted":true},{"name":"Team","price":69,"period":"month","features":["2,000 tasks/month","25 users","Shared folders"]},{"name":"Enterprise","price":"Custom","features":["Unlimited users","Advanced permissions","Custom support"]}]}'::jsonb WHERE slug = 'zapier-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://make.com/en/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["1,000 ops/month","2 active scenarios","15 min interval"]},{"name":"Core","price":10.59,"period":"month","features":["10,000 ops/month","Unlimited scenarios","1 min interval"],"highlighted":true},{"name":"Pro","price":18.82,"period":"month","features":["Priority execution","Full-text search","Advanced features"]},{"name":"Teams","price":34.12,"period":"month","features":["Team roles","Scenario templates","Collaboration"]}]}'::jsonb WHERE slug = 'make';

-- Presentation Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":12,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://beautiful.ai/pricing","tiers":[{"name":"Pro","price":12,"period":"month","features":["Unlimited slides","AI content generation","PowerPoint export"],"highlighted":true},{"name":"Team","price":40,"period":"user/month","features":["All Pro features","Brand kit","Slide library"]},{"name":"Enterprise","price":"Custom","features":["SSO","Priority support","Advanced analytics"]}]}'::jsonb WHERE slug = 'beautiful-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://gamma.app/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["400 AI credits","Basic features","Gamma branding"]},{"name":"Plus","price":10,"period":"month","features":["Unlimited AI","No branding","20 cards/presentation"],"highlighted":true},{"name":"Pro","price":20,"period":"month","features":["Advanced AI models","Analytics","Priority support"]},{"name":"Business","price":40,"period":"user/month","features":["Team features","Custom themes","Admin controls"]}]}'::jsonb WHERE slug = 'gamma';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://tome.app/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Limited AI credits","Basic features","Tome branding"]},{"name":"Pro","price":16,"period":"month","features":["Unlimited AI","Custom branding","PDF export"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["SSO","Custom AI tuning","Priority support"]}]}'::jsonb WHERE slug = 'tome';

-- Marketing & SEO Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":69,"hasFreeTrial":true,"freeTrialDays":7,"pricingPageUrl":"https://surferseo.com/pricing","tiers":[{"name":"Essential","price":69,"period":"month","features":["30 articles/month","Content Editor","SERP Analyzer"]},{"name":"Scale","price":129,"period":"month","features":["100 articles/month","Audit","All features"],"highlighted":true},{"name":"Scale AI","price":219,"period":"month","features":["100 AI articles/month","Auto-optimize","Advanced features"]},{"name":"Enterprise","price":"Custom","features":["Custom limits","API access","Dedicated support"]}]}'::jsonb WHERE slug = 'surfer-seo';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":15,"hasFreeTrial":true,"freeTrialDays":5,"pricingPageUrl":"https://frase.io/pricing","tiers":[{"name":"Solo","price":15,"period":"month","features":["4 articles/month","Basic SERP","Content briefs"]},{"name":"Basic","price":45,"period":"month","features":["30 articles/month","Full SERP","AI Writer"],"highlighted":true},{"name":"Team","price":115,"period":"month","features":["Unlimited articles","3 users","Collaboration"]}]}'::jsonb WHERE slug = 'frase';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":false,"pricingPageUrl":"https://phrasee.co/pricing","tiers":[{"name":"Enterprise","price":"Custom","features":["AI language generation","Brand voice","Campaign optimization"],"highlighted":true}]}'::jsonb WHERE slug = 'phrasee';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":49,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://lately.ai/pricing","tiers":[{"name":"Starter","price":49,"period":"month","features":["1 user","5 social channels","Basic AI"]},{"name":"Pro","price":179,"period":"month","features":["3 users","15 channels","Full AI features"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Unlimited users","Custom training","API access"]}]}'::jsonb WHERE slug = 'lately';

-- Sales & Customer Service
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0.99,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://intercom.com/pricing","tiers":[{"name":"Fin AI Agent","price":0.99,"period":"resolution","features":["AI-powered support","24/7 availability","Multi-language"],"highlighted":true},{"name":"Essential","price":29,"period":"seat/month","features":["Shared inbox","Basic automation","Live chat"]},{"name":"Advanced","price":85,"period":"seat/month","features":["Advanced automation","Custom bots","Reporting"]}]}'::jsonb WHERE slug = 'intercom-fin';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://drift.com/pricing","tiers":[{"name":"Premium","price":"Custom","features":["Live chat","Chatbots","Meetings"]},{"name":"Advanced","price":"Custom","features":["AI features","ABM","Advanced routing"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Custom AI","Dedicated support","SLA"]}]}'::jsonb WHERE slug = 'drift';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":7,"pricingPageUrl":"https://tidio.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["50 conversations","Live chat","Basic bots"]},{"name":"Starter","price":29,"period":"month","features":["100 conversations","All channels","Analytics"],"highlighted":true},{"name":"Growth","price":59,"period":"month","features":["Unlimited conversations","AI chatbots","A/B testing"]}]}'::jsonb WHERE slug = 'tidio';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://botpress.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["5 bots","2,000 messages/month","Community support"]},{"name":"Plus","price":89,"period":"month","features":["20 bots","250K messages/month","Priority support"],"highlighted":true},{"name":"Team","price":495,"period":"month","features":["100 bots","1M messages/month","SSO"]}]}'::jsonb WHERE slug = 'botpress';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":55,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://zendesk.com/pricing","tiers":[{"name":"Suite Team","price":55,"period":"agent/month","features":["Ticketing","Messaging","Basic AI"]},{"name":"Suite Growth","price":89,"period":"agent/month","features":["Self-service","Automation","AI agents"],"highlighted":true},{"name":"Suite Professional","price":115,"period":"agent/month","features":["Advanced AI","Skills routing","Analytics"]}]}'::jsonb WHERE slug = 'zendesk-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://freshdesk.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["10 agents","Email ticketing","Knowledge base"]},{"name":"Growth","price":15,"period":"agent/month","features":["Automation","Custom fields","Marketplace"],"highlighted":true},{"name":"Pro","price":49,"period":"agent/month","features":["Freddy AI","Round-robin","CSAT surveys"]},{"name":"Enterprise","price":79,"period":"agent/month","features":["Advanced AI","Sandbox","Audit log"]}]}'::jsonb WHERE slug = 'freshdesk-freddy';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":false,"pricingPageUrl":"https://gong.io/pricing","tiers":[{"name":"Platform","price":"Custom","features":["Call recording","AI analysis","Coaching insights"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Advanced AI","CRM sync","Custom integrations"]}]}'::jsonb WHERE slug = 'gong';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://chorus.ai/pricing","tiers":[{"name":"Business","price":"Custom","features":["Conversation intelligence","AI insights","Basic analytics"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Advanced AI","Custom integrations","Dedicated support"]}]}'::jsonb WHERE slug = 'chorus';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":false,"pricingPageUrl":"https://outreach.io/pricing","tiers":[{"name":"Standard","price":"Custom","features":["Sequences","Email automation","Basic AI"]},{"name":"Professional","price":"Custom","features":["Advanced analytics","AI recommendations","Governance"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Custom AI","Advanced security","SSO"]}]}'::jsonb WHERE slug = 'outreach';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://apollo.io/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["60 email credits/month","Basic filters","Limited features"]},{"name":"Basic","price":49,"period":"user/month","features":["900 email credits/month","Sequences","Intent data"],"highlighted":true},{"name":"Professional","price":79,"period":"user/month","features":["1,200 credits/month","Advanced filters","Dialer"]},{"name":"Organization","price":119,"period":"user/month","features":["Custom credits","CRM enrichment","Custom reports"]}]}'::jsonb WHERE slug = 'apollo-io';

-- HR & Recruiting
UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://hirevue.com/pricing","tiers":[{"name":"Essential","price":"Custom","features":["Video interviews","Basic AI","Scheduling"]},{"name":"Premium","price":"Custom","features":["Advanced AI","Assessments","Analytics"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Custom AI models","Integrations","Dedicated support"]}]}'::jsonb WHERE slug = 'hirevue';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":false,"pricingPageUrl":"https://eightfold.ai/pricing","tiers":[{"name":"Talent Intelligence","price":"Custom","features":["AI matching","Skills insights","DEI analytics"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Full platform","Custom AI","Integrations"]}]}'::jsonb WHERE slug = 'eightfold';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://textio.com/pricing","tiers":[{"name":"Business","price":"Custom","features":["Job post optimization","AI suggestions","Analytics"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Custom training","Integrations","API access"]}]}'::jsonb WHERE slug = 'textio';

-- Finance & Analytics
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://alpaca.markets/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Commission-free trading","Basic API","Paper trading"]},{"name":"Unlimited","price":99,"period":"month","features":["All data","Premium API","Priority support"],"highlighted":true}]}'::jsonb WHERE slug = 'alpaca';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":false,"pricingPageUrl":"https://kensho.com","tiers":[{"name":"Enterprise","price":"Custom","features":["AI analytics","NLP tools","Data extraction"],"highlighted":true}]}'::jsonb WHERE slug = 'kensho';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":false,"pricingPageUrl":"https://kavout.com","tiers":[{"name":"Enterprise","price":"Custom","features":["AI stock analysis","K Score","Portfolio tools"],"highlighted":true}]}'::jsonb WHERE slug = 'kavout';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://pecan.ai/pricing","tiers":[{"name":"Growth","price":"Custom","features":["Predictive models","AutoML","Basic support"]},{"name":"Enterprise","price":"Custom","features":["Unlimited models","Custom integrations","Dedicated support"],"highlighted":true}]}'::jsonb WHERE slug = 'pecan-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":75,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://obviously.ai/pricing","tiers":[{"name":"Starter","price":75,"period":"month","features":["3 models","10K predictions","Basic support"]},{"name":"Professional","price":200,"period":"month","features":["10 models","100K predictions","Priority support"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Unlimited models","Custom integrations","Dedicated support"]}]}'::jsonb WHERE slug = 'obviously-ai';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://monkeylearn.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["300 queries/month","1 model","Community support"]},{"name":"Team","price":299,"period":"month","features":["10K queries/month","3 models","Priority support"],"highlighted":true},{"name":"Business","price":999,"period":"month","features":["100K queries/month","10 models","Custom training"]}]}'::jsonb WHERE slug = 'monkeylearn';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":15,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://tableau.com/pricing","tiers":[{"name":"Viewer","price":15,"period":"user/month","features":["View & interact","Basic features","Dashboard access"]},{"name":"Explorer","price":42,"period":"user/month","features":["Self-service analytics","Web editing","Ask Data"],"highlighted":true},{"name":"Creator","price":75,"period":"user/month","features":["Full authoring","Prep Builder","All features"]}]}'::jsonb WHERE slug = 'tableau-ai';

-- Research & Academic
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://consensus.app/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["20 searches/month","Basic features","Limited AI"]},{"name":"Plus","price":6.99,"period":"month","features":["Unlimited searches","AI summaries","Export"],"highlighted":true},{"name":"Premium","price":12.99,"period":"month","features":["All features","Priority support","Team features"]}]}'::jsonb WHERE slug = 'consensus';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://elicit.org/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["5,000 credits","Basic search","Limited AI"]},{"name":"Plus","price":10,"period":"month","features":["12,000 credits/month","Full AI features","Priority access"],"highlighted":true},{"name":"Pro","price":42,"period":"month","features":["50,000 credits/month","Team features","API access"]}]}'::jsonb WHERE slug = 'elicit';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://semanticscholar.org","tiers":[{"name":"Free","price":0,"period":"forever","features":["Full access","AI-powered search","Paper recommendations"]}]}'::jsonb WHERE slug = 'semantic-scholar';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://scholarcy.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["3 articles/day","Basic summaries","Browser extension"]},{"name":"Personal","price":9.99,"period":"month","features":["Unlimited articles","Library sync","Full features"],"highlighted":true},{"name":"Team","price":7.99,"period":"user/month","features":["Team workspace","Shared libraries","Admin tools"]}]}'::jsonb WHERE slug = 'scholarcy';

-- Legal
UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":7,"pricingPageUrl":"https://casetext.com/pricing","tiers":[{"name":"Essentials","price":"Custom","features":["Legal search","CoCounsel AI","Brief analysis"]},{"name":"Professional","price":"Custom","features":["All features","Advanced AI","Integrations"],"highlighted":true}]}'::jsonb WHERE slug = 'casetext';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":false,"pricingPageUrl":"https://harvey.ai","tiers":[{"name":"Enterprise","price":"Custom","features":["Legal AI","Document analysis","Contract review"],"highlighted":true}]}'::jsonb WHERE slug = 'harvey-ai';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://luminance.com","tiers":[{"name":"Business","price":"Custom","features":["Contract AI","Due diligence","Negotiation"]},{"name":"Enterprise","price":"Custom","features":["Full platform","Custom AI","Integrations"],"highlighted":true}]}'::jsonb WHERE slug = 'luminance';

-- Design Tools
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":20,"hasFreeTrial":false,"pricingPageUrl":"https://looka.com/pricing","tiers":[{"name":"Basic Logo","price":20,"period":"one-time","features":["1 logo file","Low-res PNG","Basic colors"]},{"name":"Premium Logo","price":65,"period":"one-time","features":["High-res files","Vector files","Color variations"],"highlighted":true},{"name":"Brand Kit","price":96,"period":"one-time","features":["Full brand package","Social templates","Business cards"]}]}'::jsonb WHERE slug = 'looka';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://khroma.co","tiers":[{"name":"Free","price":0,"period":"forever","features":["AI color palettes","Unlimited combinations","Personal use"]}]}'::jsonb WHERE slug = 'khroma';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://uizard.io/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["2 projects","Basic features","Limited AI"]},{"name":"Pro","price":12,"period":"month","features":["Unlimited projects","Full AI features","Export"],"highlighted":true},{"name":"Business","price":39,"period":"month","features":["Team collaboration","Custom themes","Priority support"]}]}'::jsonb WHERE slug = 'uizard';

-- Adobe & Creative
UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://firefly.adobe.com/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["25 credits/month","Basic generation","Watermarked"]},{"name":"Premium","price":4.99,"period":"month","features":["100 credits/month","No watermark","Commercial use"],"highlighted":true},{"name":"Creative Cloud","price":59.99,"period":"month","features":["1,000 credits/month","All Adobe apps","Full features"]}]}'::jsonb WHERE slug = 'adobe-firefly';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://aws.amazon.com/codewhisperer/pricing","tiers":[{"name":"Individual","price":0,"period":"forever","features":["Code suggestions","Security scans","Reference tracker"]},{"name":"Professional","price":19,"period":"user/month","features":["Admin controls","SSO","Policy management"],"highlighted":true}]}'::jsonb WHERE slug = 'codewhisperer';

UPDATE "Tool" SET "pricingDetails" = '{"hasFreeTrial":true,"freeTrialDays":14,"pricingPageUrl":"https://ada.cx/pricing","tiers":[{"name":"Core","price":"Custom","features":["AI customer service","Automated resolution","Analytics"]},{"name":"Advanced","price":"Custom","features":["Advanced AI","Integrations","Custom training"],"highlighted":true},{"name":"Enterprise","price":"Custom","features":["Full platform","Dedicated support","SLA"]}]}'::jsonb WHERE slug = 'ada';

UPDATE "Tool" SET "pricingDetails" = '{"startingPrice":0,"hasFreeTrial":false,"pricingPageUrl":"https://mistral.ai/pricing","tiers":[{"name":"Free","price":0,"period":"forever","features":["Le Chat access","Basic models","Personal use"]},{"name":"Le Chat Pro","price":14.99,"period":"month","features":["Premium models","Priority access","Higher limits"],"highlighted":true},{"name":"API","price":0.0001,"period":"token","features":["Pay-per-use","All models","Commercial use"]}]}'::jsonb WHERE slug = 'mistral';
